# Generated by Django 5.0 on 2023-12-04 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_initial'),
    ]

    operations = [
    ]
