# Generated by Django 5.0 on 2023-12-04 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittlelemonAPI', '0002_initial'),
    ]

    operations = [
    ]
