# Generated by Django 5.0 on 2023-12-04 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittlelemonAPI', '0003_auto_20231204_2108'),
    ]

    operations = [
    ]
